### ISSUE TITLE
revalidatedPolicy returns policy which ignores options like "shared=false"

### ISSUE THREAD

**Issue by adityapatadia** [kornelski/http-cache-semantics#12]
When we get a new policy from 
```javascript
const {policy, modified} = oldPolicy.revalidatedPolicy(newRequest, newResponse);
```
The returned `policy` has `shared, cacheHeuristic, immutableMinTimeToLive, ignoreCargoCult` set to default. Ideally they should be set as same as original policy.

**Comment by adityapatadia** [comment]
@kornelski can you look into this?

**Comment by kornelski** [comment]
Yes, that's definitely a bug. 

I suppose this line is responsible:

```js
policy: new this.constructor(request, newResponse),
```

and it should receive options arg too.

Another solution could be to use `_fromObject` or such internal constructor, which might be marginally more efficient, although I'm worried it may be fragile due to needing additional parsed fields.
