### ISSUE TITLE
How to use this in proxy?

### ISSUE THREAD

**Issue by gajus** [kornelski/http-cache-semantics#21]
I am trying to implement cache in a custom Node.js proxy that is running across multiple machines. The problem is the `satisfiesWithoutRevalidation` method – it assumes that `CachePolicy` object is aware of previous requests, which might not be the case.

What would be the risk of using `CachePolicy` without `satisfiesWithoutRevalidation`? Effectively, if I want to rely only on `Cache-Control` as dictated by the response.

**Comment by gajus** [comment]
Something like this:

```js
const response = async (context, requestDefinition, responseDefinition) => {
  const fingerprint = context.cacheInterceptor.fingerprint;

  const cachePolicy = new CachePolicy(requestDefinition.request, responseDefinition.response, {
    ignoreCargoCult: true,
    immutableMinTimeToLive: 24 * 3600 * 1000,
    shared: true,
    trustServerDate: false
  });

  if (cachePolicy.storable() && fingerprint) {
    const data = {
      fingerprint,
      method: requestDefinition.request.method,
      requestHeaders: requestDefinition.request.headers,
      responseBody: responseDefinition.response.body || null,
      responseHeaders: responseDefinition.response.headers,
      statusCode: responseDefinition.response.statusCode,
      url: requestDefinition.request.url
    };

    await writeCache(configuration.redisClient, data, Math.min(cachePolicy.timeToLive(), MAX_EXPIRATION_TIME));
  }

  if (!responseDefinition.response.headers['x-rayman-cache-hit']) {
    return setIn(responseDefinition, ['response', 'headers', 'x-rayman-cache-hit'], 'false');
  }

  return responseDefinition;
};

```

**Comment by kornelski** [comment]
It would be incorrect, because:

* It's not possible to correctly decide whether something is a cache hit without looking at both request and response. That's a hard requirement of HTTP semantics.

* It's not valid to return a previous HTTP response unmodified. You have to update things like the `Age` header and strip some headers. `cachePolicy` has a method for that.

`cachePolicy` has `.toObject()` so that you can store them instead of the response headers.
